version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: dockers/fastapi/Dockerfile
    volumes:
      - ./model:/app/model
    ports:
      - 8000:8000
    command: uvicorn scripts.api_main:app --reload --host 0.0.0.0

