version: "3.8"

services:
  jenkins:
    image: wenliang/model-productization-jenkins:clean-22.02
    ports:
      - "8080:8080"
    volumes:
      # - ./jenkins_home_on_host:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ./clean
